# Generated by Django 5.2 on 2025-04-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glucose_readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glucosereading',
            old_name='value',
            new_name='glucose_level',
        ),
        migrations.RenameField(
            model_name='glucosereading',
            old_name='timestamp',
            new_name='reading_datetime',
        ),
    ]
